import { NextResponse } from "next/server";

export async function POST(req: Request) {
  const { prompt } = await req.json();

  if (!prompt) {
    return NextResponse.json(
      { error: "Prompt missing" },
      { status: 400 }
    );
  }

  let result = "";

  if (prompt.toLowerCase().includes("ai")) {
    result =
      "Artificial Intelligence is a way for computers to learn from data and make decisions similar to humans.";
  } else if (prompt.toLowerCase().includes("startup")) {
    result =
      "Startups are small teams building products under uncertainty, focusing on speed, learning, and iteration.";
  } else {
    result =
      "This is a demo response generated by a local inference engine simulating AI behavior.";
  }

  return NextResponse.json({ result });
}

